### ISSUE TITLE
Solving failure: "github.com/coreos/go-systemd/util" imports "github.com/coreos/go-systemd/v22/internal/dlopen", which contains malformed code: no package exists at "github.com/coreos/go-systemd/v22/internal/dlopen"

### ISSUE THREAD

**Issue by ThinkingXuan** [coreos/go-systemd#338] opened 2020-07-22 13:06 UTC

**Comment by lucab** [comment] 2020-07-23 07:39
This is likely due to your source project using Go module and a wrong import path.
The correct import path for the `util` module would be `github.com/coreos/go-systemd/v22/util`.

**Comment by lucab** [comment] 2020-07-27 07:39
Closing as a duplicate of https://github.com/coreos/go-systemd/issues/321.

**Closed by lucab** 2020-07-27 07:39 UTC
Labels: area/gomod-fallout
