### ISSUE TITLE
get compilation error when use sdjournal

### ISSUE THREAD

**Issue by AdoHe** [coreos/go-systemd#201] opened 2016-10-10 00:36 UTC
FYI. When I test sdjournal, I got this error:
```
systemd/sd-journal.h: No such file or directory
compilation terminated
```
@jonboulle

**Comment by lucab** [comment] 2016-10-10 07:25
Hi @AdoHe, I'm unfortunately missing a bit of context regarding your report.

How are you building this? Which OS and version? In order to build the `sdjournal` package you need to have the `libsystemd` development/headers files available in your system search path; are they installed?

**Comment by darkonie** [comment] 2016-10-14 00:13
@AdoHe I am pretty sure you need `libsystemd` headers. If you are using ubuntu/debian you can just run `apt-get update && apt-get install libsystemd-dev`.

**Comment by AdoHe** [comment] 2016-10-14 00:16
@lucab @darkonie yes, I am confirm this, thanks very much.

**Comment by lucab** [comment] 2016-10-14 07:46
@AdoHe Thanks for following up. Not a bug, closing.

**Closed by lucab** 2016-10-14 07:46 UTC
Labels: needs/more-information

**Comment by heartbeat2015** [comment] 2019-07-23 12:54
what's package for centos

**Comment by heartbeat2015** [comment] 2019-07-23 12:57
yum install systemd-devel   can work on centos7
